language: java
addons:
  sonarcloud:
    organization: "mtj-mjc"
    token:
      secure: "Oa3o3WEzLSiVad6vvXEEV3DiFlXX70JSh/oqw3F9bczjta6VvYKeA/YDrTA4o7AHHRPLhm8jAb4kx23Sve7xNembhNym7XHRtvAuyBBAUqk5pwiyg4c2AKfhags+grQgCCl88E+jiI2A0zjmQtBFkBRWkdRuuh5LX0rtJCzG5DLsEfo9UynzFsqXAT7Lh2exJ38sx+QNooYDUpbnB7Fqi6/S+XEg6rPnBrTr0JF7zpeFFZGGjl0vJCcM7v+TL1UcfatHdTOsq05wi7pojzUCB1iIImzrDiqQNKUzbUsC/tfQZON4qMvUgkc33pLlr4XdFcYb2GMNDhDtc1XpuSc0P5q1drdcWOXyLRTC1/Hw3zDEZRQbJMgsI/eIM2E7Tz5sC9FFTtDwrzc5zPA0Oo47+yPrOSNIReGpuOlEfXubxXo77Oj7cQ7VGHRnkmJpO0TfEryt9ZCkq1TONGh1Houaq+BRGfPFo3kpVEBKiAcndPisfhOLh23U5vr9MKvursWcLRPyGIEe+Xh+qzwghaczGg8jNLy5zcfYoTq5uH/4vJP6AmWLPgjACxxyPsB6Sj938DOnujFwJ5lGofKCk+Gj3fIJU0/72ESZ76R6fi3ICUlWiJxYueAzKi0BLX8gdtVJmW5eWoS2u0ouCuUo8CHq168pa12a/1G7L6ZRY9W42yo=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn -s travis.settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mtj-mjc_swat deploy

deploy:
  provider: releases
  api_key:
    secure: "ldbC9A8xWdd9hBxAPDid97S/7CTdN+TLwrdUXVFDiJO2pvjpsMuhdho0x6Af7Kza2PmzqGPoAEMeroWW5vKoSNiSGAEa9Lqa7aTldEFkOI21EAA9LC13VLV4IMRsMd1hpKaZEK9S85Z9HoxquY0WyABcdZKOD4WgzKq4Apr76efUvVmz5aTHNEnDFCnxvDrWDdA+WGIexazxcLNeyIsSZ6+AiUIvnNWgeSXXbRtiGMjT16NOEiUD+jI8E9hdCH9owL67xK5dcuUpCiL2q+w11cQkt0VfPjrfsFrwVAdf8QmSQXUSgKt52SOxVDjZWjbyz1tQzCX+TNb1z6Z2Ern9GSlysWjVcyx0mMmU3Ezjtzs2vShlJfGojFXItPGaox5lNxtU9RYHS1tvZ+g/loOKq+3FMMkUx59CrnZ9Qh/Hh2YemGEzximFkXkCHmdfLjhNfAmlBq+WO6iuQgBJBLeMQg3LTOcfKT0NO0MTZVLHNST15Pyqtkr/C7UIzScxPrMy2Z0TGCqCxzcGFhLmfn5zgjbYvzevItBZh0UDTpVEh0N3Z8dvWqMMtnJUAVHM3dVRdK6jnJy3JJpWSgUFAQxC8wJVZig7pBkvFzzLYO+WWUOK6RgZoWNe02DMFqOuomXIEicz2z/Mm8mGNjTsmwKWGuOICz03Trg3zEr9lG6dqUs="
  file_glob: true
  file: 
    - "gateway/target/*service.jar"
    - "order_management/target/*service.jar"
    - "product_management/target/*service.jar"
    - "user_management/target/*service.jar"
  skip_cleanup: true
  on:
    tags: true
